baseURL = 'https://blackboxdelta.com/'
languageCode = 'en-us'
title = 'Black Box Delta'
theme = 'ananke'

DefaultContentLanguage = "en"
enableRobotsTXT = true
buildDrafts = true
Paginate = 8

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = "img/bbd-logo-nav.svg"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page:
# https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-gray"
recent_posts_number = 10

#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"